# Конфигурация Dependabot для автоматизации обновлений зависимостей
version: 2
updates:
  # 🔹 1. Обновление Go-зависимостей
  - package-ecosystem: "gomod"
    directory: "/"  # Корень репозитория, где находится go.mod
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Явное указание версий для игнорирования
      - dependency-name: "gvisor.dev/gvisor"
        versions: ["*"]
      - dependency-name: "github.com/mymmrac/telego"
        versions: ["*"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Группировка обновлений
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    rebase-strategy: "auto"
          
  # 🔹 2. Обновление GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"  # Директория с GitHub Actions workflows
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
    rebase-strategy: "auto"
          
  # 🔹 3. Обновление Docker-зависимостей
  - package-ecosystem: "docker"
    directory: "/"  # Директория с Dockerfile
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    # Если нужно игнорировать определенные обновления, раскомментируйте
    # ignore:
    #   - dependency-name: "node"
    #     versions: ["13.x", "15.x"]
    rebase-strategy: "auto"
