version: 2
updates:
  # 🔹 1. Обновление Go-зависимостей
  - package-ecosystem: "gomod"
    directory: "/"  # Корень репозитория, где находится go.mod
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "gvisor.dev/gvisor"
      - dependency-name: "github.com/mymmrac/telego"
    # Разрешаем обновление как прямых, так и транзитивных зависимостей
    allow:
      - dependency-type: "all"
    # Оптимизация группировки зависимостей
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Создаем отдельную группу для критических обновлений
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
          
  # 🔹 2. Обновление GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
          
  # 🔹 3. Обновление Docker-зависимостей
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "civisrom"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    versioning-strategy: auto
