---
services:
  ui:
    build:
      context: .
      args:
        ANTIZAPRET: "${BUILD_WITH_ANTIZAPRET:-0}"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    container_name: 3x-ui
    hostname: 3x-ui
    networks:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.3x-ui.rule=Host(`${XUI_PANEL_DOMAIN}`)"
      - "traefik.http.routers.3x-ui.service=3x-ui"
      - "traefik.http.routers.3x-ui.entrypoints=https"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"
      #
      - "traefik.http.routers.3x-ui-sub.rule=Host(`${XUI_SUB_DOMAIN}`)"
      - "traefik.http.routers.3x-ui-sub.service=3x-ui-sub"
      - "traefik.http.routers.3x-ui-sub.entrypoints=https"
      - "traefik.http.services.3x-ui-sub.loadbalancer.server.port=2096"
      #
      - "traefik.tcp.routers.vless.rule=HostSNI(`${XUI_VLESS_SNI}`)"
      - "traefik.tcp.routers.vless.tls.passthrough=true"
      - "traefik.tcp.routers.vless.service=3x-ui-inbound-443"
      - "traefik.tcp.services.3x-ui-inbound-443.loadbalancer.server.port=443"
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      PUID: 1000
      PGID: 1000
      XRAY_VMESS_AEAD_FORCED: "false"
      TZ: Europe/Moscow
      XUI_SERVER_IP: "${XUI_SERVER_IP}"
    tty: true
    restart: unless-stopped

networks:
  traefik:
    external: true