name: Question
description: Describe this issue template's purpose here.
title: "[Question]: "
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: I have a question, ..., how can I solve it?
    validations:
      required: true
